import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import {  LoginProvider, RegisterProvider } from "./context/AuthContext";

export const metadata: Metadata = {
  title: "dream",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <RegisterProvider>
        <LoginProvider>
        <Navbar />
        
          <div className="flex flex-col min-h-screen">{children}</div>
        
        <Footer />
        </LoginProvider>
        </RegisterProvider>
       
      </body>
    </html>
  );
}
