import type { Metadata } from "next";

import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";  
import { CartProvider } from "./context/CartContext";
import { LoginProvider } from "./context/LoginContext";
import { AuthProvider } from "./context/AuthContext";

export const metadata: Metadata = {
  title: "dream",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AuthProvider>
      
        <LoginProvider>
       
          <CartProvider>
        <Navbar />
        
          <div className="flex flex-col min-h-screen">{children}</div>
        
        <Footer />
        </CartProvider>
        
        </LoginProvider>
      
       </AuthProvider>
      </body>
    </html>
  );
}



